import {
  BookOpen, FolderKanban, Code, FileCode, Rocket, Shield, Brain,
  Terminal, Database, Cloud, Server, Globe, Lock, Key, Bell,
  MessageSquare, Users, UserCheck, UserPlus, Archive, Bookmark,
  Briefcase, Building2, Calendar, Camera, Clipboard, Clock,
  Cog, Compass, Contact, Crown, Download, FileText, Flag,
  Flame, Folder, FolderTree, Gem, Gift, GraduationCap, Heart,
  Home, Image, Inbox, Info, Layers, Layout, Lightbulb, Link2,
  Mail, Map, Megaphone, Monitor, Moon, MousePointer2, Music,
  Network, Notebook, Package, Paintbrush, Palette, Paperclip,
  Phone, PieChart, Pin, Plane, Play, Printer, Puzzle, Radio,
  Receipt, RefreshCw, Search, Send, Share2, ShoppingBag,
  Signal, Sliders, Smile, Speaker, Star, Sun, Table, Tag,
  Target, ThumbsUp, Ticket, Trash2, Trophy, Truck, Upload,
  Video, Wifi, Wind, Zap, ZoomIn, Blocks, Bot, ChartArea,
  ChartBar, ChartLine, CircleDot, CloudLightning, CloudRain,
  Dices, Ear, Eye, Fingerprint, FlaskConical, Ghost, GitBranch,
  GitCommit, GitPullRequest, Hammer, HardDrive, Headphones,
  Microscope, Music4, Orbit, Rabbit, Scan, Scissors, Ship,
  Skull, Snowflake, Swords, TrafficCone, Umbrella, Waves,
  Activity, Airplay, AlarmClock, AlertCircle, AlertTriangle,
  AlignCenter, AlignJustify, AlignLeft, AlignRight, Anchor,
  Annoyed, Aperture, Apple, ArrowBigDown, ArrowBigLeft,
  ArrowBigRight, ArrowBigUp, ArrowDown, ArrowLeft, ArrowRight,
  ArrowUp, Asterisk, AtSign, Atom, Award, Axe, Baby, BadgeCheck,
  BadgeDollarSign, BadgePercent, BaggageClaim, Ban, Bandage,
  Banknote, BarChart2, BarChart3, BarChart4, BarChartHorizontal,
  Baseline, Bath, Battery, BatteryCharging, BatteryFull,
  BatteryMedium, BatteryWarning, Beaker, Bean, Beer, Bike,
  Binary, Biohazard, Bird, Bitcoin, Blinds, Bluetooth,
  Bold, Bomb, Bone, BookmarkPlus, BoomBox, Box, Brackets,
  Braces, Bug, Bus, Cable, CakeSlice, Calculator, CalendarCheck,
  CalendarClock, CalendarHeart, CalendarPlus, CalendarX,
  CandlestickChart, Car, Carrot, CaseLower, CaseSensitive,
  CaseUpper, Cast, Cctv, Check, CheckCircle, CheckSquare,
  ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight,
  ChevronUp, ChevronsDownUp, ChevronsLeftRight, Church,
  Cigarette, Circle, CircuitBoard, Clapperboard, CloudCog,
  CloudDrizzle, CloudFog, CloudMoon, CloudOff, CloudSnow,
  CloudSun, Cloudy, Club, Coffee, Columns, Combine, Command,
  Cookie, Copy, CopyCheck, CornerDownLeft, CornerDownRight,
  CornerRightDown, CornerRightUp, CornerUpLeft, CornerUpRight,
  Cpu, CreditCard, Cross, Crosshair, CupSoda, Currency,
  DatabaseBackup, DatabaseZap, Delete, Diamond, Diff,
  Disc2, Disc3, Divide, DivideCircle, DollarSign, DoorOpen,
  Droplet, Drum, Dumbbell, Edit, Edit2, Edit3,
  Egg, Equal, Eraser, Euro, Expand, ExternalLink, Factory,
  Fan, FastForward, Feather, FerrisWheel, FileEdit,
  FileInput, FileOutput, FileSearch, FileSymlink, FileWarning,
  Film, Filter, Fish, Frame, Frown, Fuel, Fullscreen,
  FunctionSquare, Gamepad2, Gauge, Gavel, GitCompare,
  GitFork, GitMerge, GlassWater, Glasses, Grab,
  Grid, Grip, GripHorizontal, GripVertical, Group, Guitar,
  Hand, HardHat, Hash, Heading1, Heading2, Heading3,
  Heading4, Heading5, Heading6, HelpCircle, Hexagon,
  Highlighter, History, Hourglass, IceCream2, Import,
  Infinity, Inspect, Italic, Joystick, KeyRound, KeySquare,
  Keyboard, Lamp, Landmark, Languages, Laptop2, Lasso,
  Laugh, Leaf, Library, LifeBuoy, Link, List, ListChecks,
  ListEnd, ListMinus, ListOrdered, ListPlus, ListStart,
  ListTodo, ListTree, ListX, Loader, Loader2, Locate,
  LocateFixed, LocateOff, LogIn, LogOut, Luggage, Magnet,
  MailCheck, MailMinus, MailOpen, MailPlus, MailX,
  MapPin, Martini, Maximize, Maximize2, Medal, Menu,
  MessageCircle, Mic, MicOff, Microchip, Milk, Minimize,
  Minus, MinusCircle, MinusSquare, Move, Move3d, Navigation,
  Navigation2, Newspaper, Nut, Octagon, Option, Outdent,
  ParkingCircle, ParkingSquare, PartyPopper,
  Pause, PauseCircle, PawPrint, PenLine, PenSquare,
  PenTool, Percent, PersonStanding, PhoneCall, PhoneOff,
  PictureInPicture2, Pilcrow, Pill, PinOff, Pipette,
  Pizza, Plug, PlugZap, Plus, PlusCircle, PlusSquare,
  PocketKnife, Pointer, Popcorn, Power, PowerOff,
  Presentation, QrCode, Quote, Radical, RadioReceiver,
  Radius, Rainbow, Rat, Redo, Redo2, RedoDot, RefreshCcw,
  Regex, Repeat, Repeat1, Repeat2, Rotate3d, Route,
  Ruler, Sandwich, Satellite, Save, Scale, ScatterChart,
  School, ScreenShare, Scroll, SendToBack, SeparatorHorizontal,
  SeparatorVertical, ShowerHead, Shrink, Shrub, Shuffle,
  Sigma, Signpost, Siren, SkipBack, SkipForward, Smartphone,
  SmartphoneCharging, SmilePlus, SortAsc, SortDesc, Space,
  SpellCheck2, Spline, Split, SprayCan, Sprout, Square,
  Squirrel, Stamp, StickyNote, StopCircle, Store,
  StretchHorizontal, StretchVertical, Strikethrough,
  Subscript, Subtitles, SunDim, SunMedium, Sunrise,
  Sunset, Superscript, SwissFranc, SwitchCamera, Syringe,
  Table2, TableProperties, TabletSmartphone, Tally1,
  Tally2, Tally3, Tally4, Tally5, Tangent, Tent,
  Timer, TimerOff, TimerReset, ToggleLeft, ToggleRight,
  Tornado,   Touchpad, TowerControl, ToyBrick, TrainTrack,
  TramFront, TrendingDown, TrendingUp, Triangle, Shirt,
  Tv, Type, Underline, Undo, Undo2, UnfoldHorizontal,
  UnfoldVertical, Ungroup, Unlink, Unplug, UserCog,
  UserMinus, UserX, Vegan, VenetianMask, Vibrate,
  VibrateOff, VideoOff, View, Voicemail, Volume1,
  Volume2, VolumeX, Vote, Wallet, Wand2, Watch,
  Webcam, Wheat, WifiOff, Wine, Workflow, WrapText,
  Wrench, type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  BookOpen, FolderKanban, Code, FileCode, Rocket, Shield, Brain,
  Terminal, Database, Cloud, Server, Globe, Lock, Key, Bell,
  MessageSquare, Users, UserCheck, UserPlus, Archive, Bookmark,
  Briefcase, Building2, Calendar, Camera, Clipboard, Clock,
  Cog, Compass, Contact, Crown, Download, FileText, Flag,
  Flame, Folder, FolderTree, Gem, Gift, GraduationCap, Heart,
  Home, Image, Inbox, Info, Layers, Layout, Lightbulb, Link2,
  Mail, Map, Megaphone, Monitor, Moon, MousePointer2, Music,
  Network, Notebook, Package, Paintbrush, Palette, Paperclip,
  Phone, PieChart, Pin, Plane, Play, Printer, Puzzle, Radio,
  Receipt, RefreshCw, Search, Send, Share2, ShoppingBag,
  Signal, Sliders, Smile, Speaker, Star, Sun, Table, Tag,
  Target, ThumbsUp, Ticket, Trash2, Trophy, Truck, Upload,
  Video, Wifi, Wind, Zap, ZoomIn, Blocks, Bot, ChartArea,
  ChartBar, ChartLine, CircleDot, CloudLightning, CloudRain,
  Dices, Ear, Eye, Fingerprint, FlaskConical, Ghost, GitBranch,
  GitCommit, GitPullRequest, Hammer, HardDrive, Headphones,
  Microscope, Music4, Orbit, Rabbit, Scan, Scissors, Ship,
  Skull, Snowflake, Swords, TrafficCone, Umbrella, Waves,
};

export const ICON_LIST = Object.keys(ICONS).sort();

export function getIcon(name: string): LucideIcon {
  return ICONS[name] || BookOpen;
}
